pipeline {
    agent {
        docker {
            image 'maven:3.8.4-openjdk-11'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn clean install'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Package') {
            steps {
                sh 'mvn package'
            }
        }
        stage('Deploy') {
            steps {
                sh 'docker build -t springboot-app .'
                sh 'docker run -p 8082:8080 springboot-app'
            }
        }
    }
}
